/users/PCS0256/lijing/.local/lib/python3.7/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "main.py", line 346, in <module>
    ins.run()
  File "main.py", line 161, in run
    training_time = self.train()
  File "main.py", line 263, in train
    self.save_model(is_best=True)
  File "main.py", line 331, in save_model
    shutil.copyfile(out_tar, best_path)
  File "/apps/python/3.7-2019.10/lib/python3.7/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
OSError: [Errno 122] Disk quota exceeded
/users/PCS0256/lijing/.local/lib/python3.7/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
--- Logging error ---
Traceback (most recent call last):
  File "/apps/python/3.7-2019.10/lib/python3.7/logging/__init__.py", line 1029, in emit
    self.flush()
  File "/apps/python/3.7-2019.10/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
OSError: [Errno 122] Disk quota exceeded
Call stack:
  File "main.py", line 346, in <module>
    ins.run()
  File "main.py", line 161, in run
    training_time = self.train()
  File "main.py", line 309, in train
    \tMRR:{round(valid_res['mrr'] * 100, 3)}\tHits@10:{round(valid_res['hits10'] * 100, 3)}\tBest:{round(self.best_valid * 100, 3)}"
Message: 'Snapshot:3\tEpoch:24\tLoss:6.817\ttranslation_Loss:2.943\tmulti_layer_Loss:2.953\tMAE_Loss:0.921\tdecompose_Loss:0.0                                                   \tMRR:20.82\tHits@10:38.91\tBest:20.86'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/apps/python/3.7-2019.10/lib/python3.7/logging/__init__.py", line 1029, in emit
    self.flush()
  File "/apps/python/3.7-2019.10/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
OSError: [Errno 122] Disk quota exceeded
Call stack:
  File "main.py", line 346, in <module>
    ins.run()
  File "main.py", line 161, in run
    training_time = self.train()
  File "main.py", line 309, in train
    \tMRR:{round(valid_res['mrr'] * 100, 3)}\tHits@10:{round(valid_res['hits10'] * 100, 3)}\tBest:{round(self.best_valid * 100, 3)}"
Message: 'Snapshot:3\tEpoch:28\tLoss:5.631\ttranslation_Loss:2.642\tmulti_layer_Loss:2.133\tMAE_Loss:0.857\tdecompose_Loss:0.0                                                   \tMRR:20.83\tHits@10:38.82\tBest:21.0'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/apps/python/3.7-2019.10/lib/python3.7/logging/__init__.py", line 1029, in emit
    self.flush()
  File "/apps/python/3.7-2019.10/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
OSError: [Errno 122] Disk quota exceeded
Call stack:
  File "main.py", line 346, in <module>
    ins.run()
  File "main.py", line 161, in run
    training_time = self.train()
  File "main.py", line 296, in train
    f'Early Stopping! Snapshot:{self.args.snapshot} Epoch: {epoch} Best Results: {round(self.best_valid * 100, 3)}'
Message: 'Early Stopping! Snapshot:3 Epoch: 32 Best Results: 21.0'
Arguments: ()
Traceback (most recent call last):
  File "main.py", line 346, in <module>
    ins.run()
  File "main.py", line 178, in run
    self.load_checkpoint(best_checkpoint)
  File "main.py", line 336, in load_checkpoint
    checkpoint = torch.load(input_file, map_location=f"cuda:{self.args.gpu}")
  File "/users/PCS0256/lijing/.local/lib/python3.7/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/users/PCS0256/lijing/.local/lib/python3.7/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
/users/PCS0256/lijing/.local/lib/python3.7/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
slurmstepd: error: *** JOB 32729854 ON p0252 CANCELLED AT 2024-11-26T00:33:07 ***
